export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const FETCH_FEATURED_PACKAGES_REQUEST = 'FETCH_FEATURED_PACKAGES_REQUEST'
export const FETCH_FEATURED_PACKAGES_SUCCESS = 'FETCH_FEATURED_PACKAGES_SUCCESS'
export const FETCH_FEATURED_PACKAGES_FAILURE = 'FETCH_FEATURED_PACKAGES_FAILURE'


export const SEND_CONTACT_US_REQUEST = 'SEND_CONTACT_US_REQUEST'
export const SEND_CONTACT_US_SUCCESS = 'SEND_CONTACT_US_SUCCESS'
export const SEND_CONTACT_US_FAILURE = 'SEND_CONTACT_US_FAILURE'

export const SEND_CUSTOM_EMAIL_REQUEST = 'SEND_CUSTOM_EMAIL_REQUEST'
export const SEND_CUSTOM_EMAIL_SUCCESS = 'SEND_CUSTOM_EMAIL_SUCCESS'
export const SEND_CUSTOM_EMAIL_FAILURE = 'SEND_CUSTOM_EMAIL_FAILURE'

export const SEND_JOIN_EMAIL_LIST_REQUEST = 'SEND_JOIN_EMAIL_LIST_REQUEST'
export const SEND_JOIN_EMAIL_LIST_SUCCESS = 'SEND_JOIN_EMAIL_LIST_SUCCESS'
export const SEND_JOIN_EMAIL_LIST_FAILURE = 'SEND_JOIN_EMAIL_LIST_FAILURE'
