export const FETCH_FEATURED_LOCATIONS_REQUEST = 'FETCH_FEATURED_LOCATIONS_REQUEST'
export const FETCH_FEATURED_LOCATIONS_SUCCESS = 'FETCH_FEATURED_LOCATIONS_SUCCESS'
export const FETCH_FEATURED_LOCATIONS_FAILURE = 'FETCH_FEATURED_LOCATIONS_FAILURE'


export const SEND_CONTACT_US_REQUEST = 'SEND_CONTACT_US_REQUEST'
export const SEND_CONTACT_US_SUCCESS = 'SEND_CONTACT_US_SUCCESS'
export const SEND_CONTACT_US_FAILURE = 'SEND_CONTACT_US_FAILURE'

export const SEND_CUSTOM_EMAIL_REQUEST = 'SEND_CUSTOM_EMAIL_REQUEST'
export const SEND_CUSTOM_EMAIL_SUCCESS = 'SEND_CUSTOM_EMAIL_SUCCESS'
export const SEND_CUSTOM_EMAIL_FAILURE = 'SEND_CUSTOM_EMAIL_FAILURE'

export const SEND_JOIN_EMAIL_LIST_REQUEST = 'SEND_JOIN_EMAIL_LIST_REQUEST'
export const SEND_JOIN_EMAIL_LIST_SUCCESS = 'SEND_JOIN_EMAIL_LIST_SUCCESS'
export const SEND_JOIN_EMAIL_LIST_FAILURE = 'SEND_JOIN_EMAIL_LIST_FAILURE'
