export const FETCH_PACKAGE_REQUEST = 'FETCH_PACKAGE_REQUEST'
export const FETCH_PACKAGE_SUCCESS = 'FETCH_PACKAGE_SUCCESS'
export const FETCH_PACKAGE_FAILURE = 'FETCH_PACKAGE_FAILURE'

export const FETCH_THINGS_TO_DO_REQUEST = 'FETCH_THINGS_TO_DO_REQUEST'
export const FETCH_THINGS_TO_DO_SUCCESS = 'FETCH_THINGS_TO_DO_SUCCESS'
export const FETCH_THINGS_TO_DO_FAILURE = 'FETCH_THINGS_TO_DO_FAILURE'

export const FETCH_YELP_TAGS_REQUEST = 'FETCH_YELP_TAGS_REQUEST'
export const FETCH_YELP_TAGS_SUCCESS = 'FETCH_YELP_TAGS_SUCCESS'
export const FETCH_YELP_TAGS_FAILURE = 'FETCH_YELP_TAGS_FAILURE'

