export const FETCH_FILTERS_REQUEST = 'FETCH_FILTERS_REQUEST'
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS'
export const FETCH_FILTERS_FAILURE = 'FETCH_FILTERS_FAILURE'

export const FETCH_PACKAGES_REQUEST = 'FETCH_PACKAGES_REQUEST'
export const FETCH_PACKAGES_SUCCESS = 'FETCH_PACKAGES_SUCCESS'
export const FETCH_PACKAGES_FAILURE = 'FETCH_PACKAGES_FAILURE'
